permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default

# Handle all paths under /mixer
include: [mixer]
exclude: [mixer/configs]  # Don't process JSON files as Jekyll pages 